name: Github pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@1.4.2

    - name: Install
      run: npm ci
    
    - name: Bundle
      run: npm build

    # Runs a set of commands using the runners shell
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
